# pre-commit-config.yaml
# See https://pre-commit.com for docs and https://pre-commit.com/hooks.html for available hooks

# ======================================================
# =======            repository hooks           ========
# ======================================================
repos:
# Official pre-commit-hooks for general checks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: pretty-format-json
        args: [--no-sort-keys, --indent=4, --autofix]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
# Format TOML and YAML files with pretty-format hooks
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
    -   id: pretty-format-yaml
        args:
        -   --autofix
        -   --indent
        -   '4'
        stages: [pre-commit]
        files: \.ya?ml$
