name: Build MkDocs documentation

on:
    push:
        branches: [main, master]

permissions:
    contents: write

jobs:
    build-documentation:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Configure Git Credentials
            run: |
                git config user.name github-actions[bot]
                git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        -   uses: ./.github/actions/setup
            with:
                python-version: '3.12'
        -   name: configure mkdocs-material cache
            uses: actions/cache@v4
            with:
                key: mkdocs-material-${{ github.run_id }}
                path: .cache
                restore-keys: |
                    mkdocs-material-
        -   name: Build documentation with mkdocs
            run: .venv/bin/mkdocs gh-deploy --force
