name: Security Scan

on: [push, pull_request]

jobs:
    security-check:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-python@v5
            with:
                python-version: '3.12'
        -   name: Install Bandit
            run: pip install bandit
        -   name: Run Bandit
            run: bandit -r . --exclude venv,.venv,.tox --skip B101
