name: CI testing [unit testing]

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   uses: ./.github/actions/setup
            with:
                python-version: '3.13'
        -   name: Run Ruff (lint + formatting + import order)
            run: .venv/bin/ruff check .
        -   name: Run Ruff format check (like Black)
            run: .venv/bin/ruff format --check .

    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12', '3.13']
        steps:
        -   uses: actions/checkout@v4
        -   uses: ./.github/actions/setup
            with:
                python-version: ${{ matrix.python-version }}
        -   name: Run tests with coverage
            run: |
                source .venv/bin/activate
                pytest --cov=omnigraph tests/
        -   name: Upload coverage report
            uses: actions/upload-artifact@v4
            with:
                name: coverage-report
                path: .coverage*
