# .github/workflows/docs.yml
name: Build MkDocs documentation

on:
    push:
        branches:
        -   main
        -   master
permissions:
    contents: write

jobs:
    build-documentation:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Configure Git Credentials
            run: |
                git config user.name github-actions[bot]
                git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        -   uses: actions/setup-python@v5
            with:
                python-version: 3.x
        -   run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

        -   name: Install uv
            run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh

        -   name: Create virtualenv and install mkdocs
            run: |
                uv venv .venv
                source .venv/bin/activate
                uv pip install ".[docs]"

        -   name: configure mkdocs-material cache
            uses: actions/cache@v4
            with:
                key: mkdocs-material-${{ env.cache_id }}
                path: .cache
                restore-keys: |
                    mkdocs-material-

        -   name: Build documentation with mkdocs
            run: uv run mkdocs gh-deploy --force
