# .github/workflows/test.yml
name: Testing [unit testing]

on: [push, pull_request]

jobs:
    unit-tests:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: 3.x

        -   name: Install uv
            run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh

        -   name: Create virtualenv and install dependencies
            run: |
                uv venv .venv
                source .venv/bin/activate
                uv pip install ".[dev,tests,docs]"
                # uv pip install pytest pytest-cov

        -   name: Run tests with coverage
            run: |
                source .venv/bin/activate
                # pytest --cov=your_package tests/
