name: Bug Report
description: Report a problem with the cookiecutter template or the generated project.
title: '[BUG] '
labels: [bug]
body:
-   type: textarea
    id: description
    attributes:
        label: Description
        description: Describe the bug clearly and concisely.
        placeholder: What happened?
    validations:
        required: true

-   type: textarea
    id: reproduce
    attributes:
        label: Steps to Reproduce
        description: Provide all steps, including Cookiecutter prompts.
        placeholder: |
            1.
            2.
            3.
    validations:
        required: true

-   type: textarea
    id: expected
    attributes:
        label: Expected Behavior
        description: Describe what you expected to happen.
    validations:
        required: true

-   type: textarea
    id: actual
    attributes:
        label: Actual Behavior / Logs
        description: Include error messages, stack traces, or relevant output.
        render: shell

-   type: input
    id: environment
    attributes:
        label: Environment
        description: Python version, OS, Cookiecutter version.
        placeholder: Python 3.12.1, Ubuntu 22.04, Cookiecutter 2.3
