name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:

    test:
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash -e {0}

        strategy:
            fail-fast: false
            matrix:
                python: [3.8, 3.9, 3.10]
                os: [ubuntu-latest, macos-latest]

        env:
            OS: ${{ matrix.os }}
            PYTHON: ${{ matrix.python }}

        steps:
        -   uses: actions/checkout@v2
        -   name: Set up Python ${{ matrix.python }}
            uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python }}
                cache: pip
                cache-dependency-path: '**/pyproject.toml'

        -   name: Install test dependencies
            run: |
                python -m pip install --upgrade pip wheel
                pip install codecov
        -   name: Install dependencies
            run: |
                pip install ".[dev,test]"
        -   name: Install pip dependencies
            run: |
                python -m pip install --upgrade pip
        -   name: Test
            env:
                MPLBACKEND: agg
                PLATFORM: ${{ matrix.os }}
                DISPLAY: :42
            run: |
                pytest -v --cov --color=yes
        -   name: Upload coverage
            env:
                CODECOV_NAME: ${{ matrix.python }}-${{ matrix.os }}
            run: |
                codecov --no-color --required --flags unittests
